import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/shared/components/Header";
import LeftSidebar from "@/shared/components/LeftSidebar";
import RightSidebar from "@/shared/components/RightSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen w-screen`}
      >
        <div className="h-full w-full grid grid-rows-[5rem_1fr] grid-cols-[22.5rem_1fr_21.25rem]">
          <Header className="col-span-3"/>
          <LeftSidebar />
          {children}
          <RightSidebar />
        </div>
      </body>
    </html>
  );
}
